-- Generated from apps/apps/aquarium/asset_directions.json by convert_to_lua_assets.py.
return {
  sealife = {
    { key = "anglerfish", name = "Anglerfish", direction = "left" },
    { key = "blowfish", name = "Blowfish", direction = "right" },
    { key = "blue_tang", name = "Blue Tang", direction = "right" },
    { key = "clownfish", name = "Clownfish", direction = "left" },
    { key = "cuttlefish", name = "Cuttlefish", direction = "right" },
    { key = "jellyfish", name = "Jellyfish", direction = "right" },
    { key = "lionfish", name = "Lionfish", direction = "right" },
    { key = "moray_eel", name = "Moray Eel", direction = "left" },
    { key = "royal_gramma", name = "Royal Gramma", direction = "left" },
    { key = "sea_turtle", name = "Sea Turtle", direction = "left" },
    { key = "seahorse", name = "Seahorse", direction = "left" },
    { key = "shark", name = "Shark", direction = "left" },
    { key = "shrimp", name = "Shrimp", direction = "left" },
  },
  diver = { key = "diver", name = "Diver", direction = "right" },
  decor = {
    { key = "anchor", name = "Anchor" },
    { key = "coral_brain", name = "Coral Brain" },
    { key = "coral_finger", name = "Coral Finger" },
    { key = "coral_tubes", name = "Coral Tubes" },
    { key = "crab", name = "Crab" },
    { key = "fan_coral", name = "Fan Coral" },
    { key = "helmet", name = "Helmet" },
    { key = "kelp_forest", name = "Kelp Forest" },
    { key = "pearl_oyster", name = "Pearl Oyster" },
    { key = "rock_arch", name = "Rock Arch" },
    { key = "sandcastle", name = "Sandcastle" },
    { key = "sea_anemone", name = "Sea Anemone" },
    { key = "shipwreck", name = "Shipwreck" },
    { key = "staghorn_coral", name = "Staghorn Coral" },
    { key = "treasure", name = "Treasure" },
  },
}
