-- Generated by tools/import_steel_samples.py; do not edit by hand.
return {
    rate = 16000,
    notes = {
        [40] = { file = "n040.pcm", frames = 40000, name = "E2" },
        [41] = { file = "n041.pcm", frames = 40000, name = "F2" },
        [43] = { file = "n043.pcm", frames = 32220, name = "G2" },
        [45] = { file = "n045.pcm", frames = 40000, name = "A2" },
        [47] = { file = "n047.pcm", frames = 40000, name = "B2" },
        [48] = { file = "n048.pcm", frames = 40000, name = "C3" },
        [50] = { file = "n050.pcm", frames = 40000, name = "D3" },
        [52] = { file = "n052.pcm", frames = 40000, name = "E3" },
        [53] = { file = "n053.pcm", frames = 40000, name = "F3" },
        [55] = { file = "n055.pcm", frames = 37116, name = "G3" },
        [57] = { file = "n057.pcm", frames = 40000, name = "A3" },
        [59] = { file = "n059.pcm", frames = 40000, name = "B3" },
        [60] = { file = "n060.pcm", frames = 40000, name = "C4" },
        [62] = { file = "n062.pcm", frames = 40000, name = "D4" },
        [64] = { file = "n064.pcm", frames = 32214, name = "E4" },
        [65] = { file = "n065.pcm", frames = 30405, name = "F4" },
        [66] = { file = "n066.pcm", frames = 28699, name = "Fs4" },
        [67] = { file = "n067.pcm", frames = 29582, name = "G4" },
    },
}
